version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    container_name: mysql_db
    volumes:
      - './initdb.sql:/docker-entrypoint-initdb.d/init.sql'
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}